import { test, expect, vi } from "vitest"
import userEvent from "@testing-library/user-event"
import { renderWithMantine } from "../../test-utilities/renderWithMantine"
import {
  getDot,
  getOrdinaryLabel,
  getSolfegeLabel,
  getSimplifiedLabel,
  getRootSpotlight,
  getRankSpotlight,
  getDecrementRankButton,
  getIncrementRootButton,
  getIncrementBothButton,
  getExtraNoteNamesSelect,
} from "../../test-utilities/componentUtilities"

import { ScalesTool } from "@scalesTool/ScalesTool"

import { AnimationOption } from "@shared/utilities/clock"
import { NaturalNote } from "@shared/utilities/naturalNote"
import { SolfegeLetter } from "@shared/utilities/solfegeLetter"
import { SimplifiedLetter } from "@shared/utilities/simplifiedLetter"


// Turn off animation
vi.mock(import("@scalesTool/initialState"), async (importOriginal) => {
  const originalModule = await importOriginal()
  const originialInitialState = originalModule.getInitialState()
  return {
    getInitialState: () => ({ ...originialInitialState, animationOption: AnimationOption.None }),
  }
})

test("<ScalesTool /> shows C major as default correctly", async () => {
  renderWithMantine(<ScalesTool />)

  const user = userEvent.setup()

  expect(
    getRootSpotlight().getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )

  expect(
    getDot(SolfegeLetter.do).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getDot(SolfegeLetter.re).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getDot(SolfegeLetter.mi).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-2")
  )
  expect(
    getDot(SolfegeLetter.fa).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-3")
  )
  expect(
    getDot(SolfegeLetter.sol).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getDot(SolfegeLetter.la).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-7")
  )
  expect(
    getDot(SolfegeLetter.ti).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-9")
  )

  expect(
    getOrdinaryLabel(NaturalNote.C).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getOrdinaryLabel(NaturalNote.C).textContent
  ).toBe(
    "C"
  )
  expect(
    getOrdinaryLabel(NaturalNote.D).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getOrdinaryLabel(NaturalNote.D).textContent
  ).toBe(
    "D"
  )
  expect(
    getOrdinaryLabel(NaturalNote.E).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-2")
  )
  expect(
    getOrdinaryLabel(NaturalNote.E).textContent
  ).toBe(
    "E"
  )
  expect(
    getOrdinaryLabel(NaturalNote.F).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-3")
  )
  expect(
    getOrdinaryLabel(NaturalNote.F).textContent
  ).toBe(
    "F"
  )
  expect(
    getOrdinaryLabel(NaturalNote.G).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getOrdinaryLabel(NaturalNote.G).textContent
  ).toBe(
    "G"
  )
  expect(
    getOrdinaryLabel(NaturalNote.A).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-7")
  )
  expect(
    getOrdinaryLabel(NaturalNote.A).textContent
  ).toBe(
    "A"
  )
  expect(
    getOrdinaryLabel(NaturalNote.B).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-9")
  )
  expect(
    getOrdinaryLabel(NaturalNote.B).textContent
  ).toBe(
    "B"
  )

  await user.selectOptions(getExtraNoteNamesSelect(), "Solfège")

  expect(
    getSolfegeLabel(SolfegeLetter.do).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.do).textContent
  ).toBe(
    "do"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.re).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.re).textContent
  ).toBe(
    "re"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.mi).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-2")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.mi).textContent
  ).toBe(
    "mi"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.fa).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-3")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.fa).textContent
  ).toBe(
    "fa"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.sol).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.sol).textContent
  ).toBe(
    "sol"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.la).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-7")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.la).textContent
  ).toBe(
    "la"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.ti).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-9")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.ti).textContent
  ).toBe(
    "ti"
  )

  await user.selectOptions(getExtraNoteNamesSelect(), "Simplified")

  expect(
    getRankSpotlight().getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )

  expect(
    getSimplifiedLabel(SimplifiedLetter.c).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.c).textContent
  ).toBe(
    "c"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.d).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.d).textContent
  ).toBe(
    "d"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.e).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-2")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.e).textContent
  ).toBe(
    "e"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.f).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-3")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.f).textContent
  ).toBe(
    "f"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.g).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.g).textContent
  ).toBe(
    "g"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.a).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-7")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.a).textContent
  ).toBe(
    "a"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.b).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-9")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.b).textContent
  ).toBe(
    "b"
  )
})

test("<ScalesTool /> shows G major as default correctly", async () => {
  renderWithMantine(<ScalesTool />)

  const user = userEvent.setup()
  await user.click(getIncrementBothButton())

  expect(
    getRootSpotlight().getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )

  expect(
    getDot(SolfegeLetter.do).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getDot(SolfegeLetter.re).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-7")
  )
  expect(
    getDot(SolfegeLetter.mi).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-9")
  )
  expect(
    getDot(SolfegeLetter.fa).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getDot(SolfegeLetter.sol).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getDot(SolfegeLetter.la).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-2")
  )
  expect(
    getDot(SolfegeLetter.ti).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-4")
  )

  expect(
    getOrdinaryLabel(NaturalNote.G).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getOrdinaryLabel(NaturalNote.G).textContent
  ).toBe(
    "G"
  )
  expect(
    getOrdinaryLabel(NaturalNote.A).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-7")
  )
  expect(
    getOrdinaryLabel(NaturalNote.A).textContent
  ).toBe(
    "A"
  )
  expect(
    getOrdinaryLabel(NaturalNote.B).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-9")
  )
  expect(
    getOrdinaryLabel(NaturalNote.B).textContent
  ).toBe(
    "B"
  )
  expect(
    getOrdinaryLabel(NaturalNote.C).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getOrdinaryLabel(NaturalNote.C).textContent
  ).toBe(
    "C"
  )
  expect(
    getOrdinaryLabel(NaturalNote.D).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getOrdinaryLabel(NaturalNote.D).textContent
  ).toBe(
    "D"
  )
  expect(
    getOrdinaryLabel(NaturalNote.E).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-2")
  )
  expect(
    getOrdinaryLabel(NaturalNote.E).textContent
  ).toBe(
    "E"
  )
  expect(
    getOrdinaryLabel(NaturalNote.F).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-4")
  )
  expect(
    getOrdinaryLabel(NaturalNote.F).textContent
  ).toBe(
    "F♯"
  )

  await user.selectOptions(getExtraNoteNamesSelect(), "Solfège")

  expect(
    getSolfegeLabel(SolfegeLetter.do).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.do).textContent
  ).toBe(
    "do"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.re).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-7")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.re).textContent
  ).toBe(
    "re"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.mi).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-9")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.mi).textContent
  ).toBe(
    "mi"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.fa).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.fa).textContent
  ).toBe(
    "fa"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.sol).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.sol).textContent
  ).toBe(
    "sol"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.la).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-2")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.la).textContent
  ).toBe(
    "la"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.ti).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-4")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.ti).textContent
  ).toBe(
    "ti"
  )

  await user.selectOptions(getExtraNoteNamesSelect(), "Simplified")

  expect(
    getRankSpotlight().getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-7")
  )

  expect(
    getSimplifiedLabel(SimplifiedLetter.c).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.c).textContent
  ).toBe(
    "c"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.d).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-7")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.d).textContent
  ).toBe(
    "d"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.e).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-9")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.e).textContent
  ).toBe(
    "e"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.f).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.f).textContent
  ).toBe(
    "f"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.g).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.g).textContent
  ).toBe(
    "g"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.a).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-2")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.a).textContent
  ).toBe(
    "a"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.b).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-4")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.b).textContent
  ).toBe(
    "b"
  )
})

test("<ScalesTool /> shows C minor correctly", async () => {
  renderWithMantine(<ScalesTool />)

  const user = userEvent.setup()
  await user.click(getDecrementRankButton())
  await user.click(getDecrementRankButton())
  await user.click(getDecrementRankButton())

  expect(
    getRootSpotlight().getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )

  expect(
    getDot(SolfegeLetter.do).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getDot(SolfegeLetter.re).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getDot(SolfegeLetter.mi).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-1")
  )
  expect(
    getDot(SolfegeLetter.fa).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-3")
  )
  expect(
    getDot(SolfegeLetter.sol).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getDot(SolfegeLetter.la).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-6")
  )
  expect(
    getDot(SolfegeLetter.ti).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-8")
  )

  expect(
    getOrdinaryLabel(NaturalNote.C).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getOrdinaryLabel(NaturalNote.C).textContent
  ).toBe(
    "C"
  )
  expect(
    getOrdinaryLabel(NaturalNote.D).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getOrdinaryLabel(NaturalNote.D).textContent
  ).toBe(
    "D"
  )
  expect(
    getOrdinaryLabel(NaturalNote.E).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-1")
  )
  expect(
    getOrdinaryLabel(NaturalNote.E).textContent
  ).toBe(
    "E♭"
  )
  expect(
    getOrdinaryLabel(NaturalNote.F).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-3")
  )
  expect(
    getOrdinaryLabel(NaturalNote.F).textContent
  ).toBe(
    "F"
  )
  expect(
    getOrdinaryLabel(NaturalNote.G).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getOrdinaryLabel(NaturalNote.G).textContent
  ).toBe(
    "G"
  )
  expect(
    getOrdinaryLabel(NaturalNote.A).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-6")
  )
  expect(
    getOrdinaryLabel(NaturalNote.A).textContent
  ).toBe(
    "A♭"
  )
  expect(
    getOrdinaryLabel(NaturalNote.B).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-8")
  )
  expect(
    getOrdinaryLabel(NaturalNote.B).textContent
  ).toBe(
    "B♭"
  )

  await user.selectOptions(getExtraNoteNamesSelect(), "Solfège")

  expect(
    getSolfegeLabel(SolfegeLetter.do).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.do).textContent
  ).toBe(
    "do"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.re).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.re).textContent
  ).toBe(
    "re"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.mi).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-1")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.mi).textContent
  ).toBe(
    "mi"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.fa).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-3")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.fa).textContent
  ).toBe(
    "fa"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.sol).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.sol).textContent
  ).toBe(
    "sol"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.la).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-6")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.la).textContent
  ).toBe(
    "la"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.ti).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-8")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.ti).textContent
  ).toBe(
    "ti"
  )

  await user.selectOptions(getExtraNoteNamesSelect(), "Simplified")

  expect(
    getRankSpotlight().getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-3")
  )

  expect(
    getSimplifiedLabel(SimplifiedLetter.a).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.a).textContent
  ).toBe(
    "a"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.b).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.b).textContent
  ).toBe(
    "b"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.c).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-1")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.c).textContent
  ).toBe(
    "c"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.d).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-3")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.d).textContent
  ).toBe(
    "d"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.e).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.e).textContent
  ).toBe(
    "e"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.f).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-6")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.f).textContent
  ).toBe(
    "f"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.g).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-8")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.g).textContent
  ).toBe(
    "g"
  )
})

test("<ScalesTool /> shows Dorian D correctly", async () => {
  renderWithMantine(<ScalesTool />)

  const user = userEvent.setup()
  await user.click(getIncrementRootButton())
  await user.click(getIncrementRootButton())

  expect(
    getRootSpotlight().getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )

  expect(
    getDot(SolfegeLetter.do).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getDot(SolfegeLetter.re).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-2")
  )
  expect(
    getDot(SolfegeLetter.mi).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-3")
  )
  expect(
    getDot(SolfegeLetter.fa).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getDot(SolfegeLetter.sol).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-7")
  )
  expect(
    getDot(SolfegeLetter.la).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-9")
  )
  expect(
    getDot(SolfegeLetter.ti).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )

  expect(
    getOrdinaryLabel(NaturalNote.D).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getOrdinaryLabel(NaturalNote.D).textContent
  ).toBe(
    "D"
  )
  expect(
    getOrdinaryLabel(NaturalNote.E).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-2")
  )
  expect(
    getOrdinaryLabel(NaturalNote.E).textContent
  ).toBe(
    "E"
  )
  expect(
    getOrdinaryLabel(NaturalNote.F).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-3")
  )
  expect(
    getOrdinaryLabel(NaturalNote.F).textContent
  ).toBe(
    "F"
  )
  expect(
    getOrdinaryLabel(NaturalNote.G).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getOrdinaryLabel(NaturalNote.G).textContent
  ).toBe(
    "G"
  )
  expect(
    getOrdinaryLabel(NaturalNote.A).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-7")
  )
  expect(
    getOrdinaryLabel(NaturalNote.A).textContent
  ).toBe(
    "A"
  )
  expect(
    getOrdinaryLabel(NaturalNote.B).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-9")
  )
  expect(
    getOrdinaryLabel(NaturalNote.B).textContent
  ).toBe(
    "B"
  )
  expect(
    getOrdinaryLabel(NaturalNote.C).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getOrdinaryLabel(NaturalNote.C).textContent
  ).toBe(
    "C"
  )

  await user.selectOptions(getExtraNoteNamesSelect(), "Solfège")

  expect(
    getSolfegeLabel(SolfegeLetter.do).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.do).textContent
  ).toBe(
    "do"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.re).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-2")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.re).textContent
  ).toBe(
    "re"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.mi).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-3")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.mi).textContent
  ).toBe(
    "mi"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.fa).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.fa).textContent
  ).toBe(
    "fa"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.sol).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-7")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.sol).textContent
  ).toBe(
    "sol"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.la).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-9")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.la).textContent
  ).toBe(
    "la"
  )
  expect(
    getSolfegeLabel(SolfegeLetter.ti).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getSolfegeLabel(SolfegeLetter.ti).textContent
  ).toBe(
    "ti"
  )

  await user.selectOptions(getExtraNoteNamesSelect(), "Simplified")

  expect(
    getRankSpotlight().getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )

  expect(
    getSimplifiedLabel(SimplifiedLetter.d).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-0")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.d).textContent
  ).toBe(
    "d"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.e).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-2")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.e).textContent
  ).toBe(
    "e"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.f).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-3")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.f).textContent
  ).toBe(
    "f"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.g).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-5")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.g).textContent
  ).toBe(
    "g"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.a).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-7")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.a).textContent
  ).toBe(
    "a"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.b).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-9")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.b).textContent
  ).toBe(
    "b"
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.c).getAttribute("class")
  ).toEqual(
    expect.stringContaining("hour-10")
  )
  expect(
    getSimplifiedLabel(SimplifiedLetter.c).textContent
  ).toBe(
    "c"
  )
})
